name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Bạn có thể thay đổi branch nếu cần
  pull_request:
    branches:
      - main  # Bạn có thể thay đổi branch nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.15.0'  # Thay đổi theo version của bạn

      # Cài đặt các dependencies
      - name: Install dependencies
        run: |
          npm install

      # Chạy các bài kiểm tra (nếu có)
      # - name: Run tests
      #   run: |
      #     npm test

      # Triển khai ứng dụng lên server qua SSH (sử dụng ngrok để có public SSH nếu cần)
      - name: Deploy to server via SSH
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          USER: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p $PORT $USER@$HOST "
            cd /home/levius/test-nodejs-ubuntu &&
            git stash && 
            git pull origin main && 
            npm install && 
            pm2 restart ecosystem.config.js
          "