name: Node.js CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Lấy mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
 
      # Cài đặt Node.js (chỉ dùng để build local nếu cần)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.15.0'  # Thay đổi nếu bạn dùng version khác
 
      # Cài đặt dependencies nếu bạn build trước khi deploy
      - name: Install dependencies
        run: |
          npm install
 
      # (Tuỳ chọn) Chạy test
      # - name: Run tests
      #   run: |
      #     npm test
 
      # Deploy lên server qua SSH
      - name: Deploy to server via SSH
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          PORT: ${{ secrets.SERVER_PORT }}
          USER: ${{ secrets.SERVER_USER }}
          PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem -p $PORT $USER@$HOST '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/'"$USER"'/test-nodejs-ubuntu &&
            git stash &&
            git pull origin main &&
            nvm use &&
            npm install &&
            pm2 restart ecosystem.config.js
          '